### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by wintsa123** [groupdocs-conversion/GroupDocs.Conversion-for-Node.js-via-Java#7]
![企业微信截图_17101292242077](https://github.com/groupdocs-conversion/GroupDocs.Conversion-for-Node.js-via-Java/assets/47288630/f09cd79b-42ab-401c-89dd-05a1af9e3fb9)
![企业微信截图_17101292343041](https://github.com/groupdocs-conversion/GroupDocs.Conversion-for-Node.js-via-Java/assets/47288630/2b6bf2a0-f33f-4bfd-ad50-8bb650f7efaa)
i dont know how to install it。。。

**Comment by MendleM** [comment]
Second this

**Comment by RakhimAimaganbetov** [comment]
Hi, `distutils` package is removed in `python version 3.12`

> It was deprecated in Python 3.10 by PEP 632 “Deprecate distutils module”. For projects still using distutils and cannot be updated to something else, the setuptools project can be installed: it still provides distutils.

use below command in your virtual environment

```pip install setuptools```
or
```pip3 install setuptools```
or
```brew install python-setuptools```

**Comment by RakhimAimaganbetov** [comment]
Hello!

As we haven't received any further responses from you, we are closing this ticket. We hope that the provided solution helped you resolve the issue.

If you have any additional questions or problems, please feel free to open a new ticket.

Thank you for reaching out!
